# Generated by Django 4.2.2 on 2023-06-06 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 6, 6, 16, 35, 15, 83111, tzinfo=datetime.timezone.utc), max_length=3),
            preserve_default=False,
        ),
    ]
