# Generated by Django 4.2 on 2023-06-07 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 6, 7, 2, 2, 1, 59148, tzinfo=datetime.timezone.utc), max_length=25),
            preserve_default=False,
        ),
    ]
