# Generated by Django 4.2 on 2023-06-07 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 6, 7, 17, 33, 4, 773142, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
