# Generated by Django 4.2 on 2023-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Desapproved', 'Desapproved')], default='Pending', max_length=50, null=True),
        ),
    ]
