# Generated by Django 4.2 on 2023-06-07 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=datetime.datetime(2023, 6, 7, 20, 52, 3, 803044, tzinfo=datetime.timezone.utc), max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am outgoing', 'I am outgoing'), ('I am antisocial', 'I am antisocial'), ('I am discret', 'I am discret'), ('I am sociable', 'I am sociable'), ('I am serious', 'I am serious'), ('', 'Select a personality')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(default=datetime.datetime(2023, 6, 7, 20, 52, 50, 18647, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'yes'), ('2', 'no')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Desapproved', 'Desapproved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
