# Generated by Django 4.2 on 2023-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_experience_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am antisocial', 'I am antisocial'), ('', 'Select a personality'), ('I am discret', 'I am discret'), ('I am sociable', 'I am sociable'), ('I am outgoing', 'I am outgoing'), ('I am serious', 'I am serious')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
