# Generated by Django 4.2.2 on 2023-06-08 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_candidate_personality_alter_candidate_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 6, 8, 15, 52, 54, 900836, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am serious', 'I am serious'), ('I am discret', 'I am discret'), ('I am antisocial', 'I am antisocial'), ('I am outgoing', 'I am outgoing'), ('I am sociable', 'I am sociable')], max_length=50, null=True),
        ),
    ]
