# Generated by Django 4.2.2 on 2023-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_candidate_file_alter_candidate_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am discret', 'I am discret'), ('I am sociable', 'I am sociable'), ('I am antisocial', 'I am antisocial'), ('I am serious', 'I am serious'), ('I am outgoing', 'I am outgoing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Desapproved', 'Desapproved')], default='Pending', max_length=50, null=True),
        ),
    ]
